# Generated by Django 5.1.2 on 2024-11-12 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_back', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
